baseURL = 'http://dayoonsuh.github.io'
languageCode = 'en-us'
title = 'This and That'
theme = 'hugo-theme-stack'

[params]
    [params.sidebar]
    emoji = "ğŸ¥"
    subtitle = "Dayoon Suh"

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "../assets/img/sorbet.JPG"

[menu]

    [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/dayoonsuh/"

        [menu.social.params]
        icon = "brand-github"

